### ISSUE TITLE
When chef_handler reloads a file, any transitive "require"ments are not reloaded as well.

### ISSUE THREAD

**Issue by kbaltrinic** [opscode-cookbooks/chef_handler#21]
We just pulled down v 1.1.9 and immediately our chef-runs broke with the following error:

```  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/box-sonar-01/recipes/default.rb
  ================================================================================
  
  NoMethodError
  -------------
  chef_handler[Chef::Handler::Datadog] (datadog::dd-handler line 30) had an error: NoMethodError: undefined method `new' for ChefHandler:Module
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/datadog/recipes/dd-handler.rb:40:in `from_file'
    /var/chef/cache/cookbooks/linux-base/recipes/default.rb:28:in `from_file'
    /var/chef/cache/cookbooks/sonarqube-cvent/recipes/default.rb:20:in `from_file'
    /var/chef/cache/cookbooks/box-sonar-01/recipes/default.rb:15:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/datadog/recipes/dd-handler.rb:
  
   33:      :api_key => node['datadog']['api_key'],
   34:      :application_key => node['datadog']['application_key'],
   35:      :use_ec2_instance_id => node['datadog']['use_ec2_instance_id'],
   36:      :notify_on_failure => node['datadog']['handler']['notify_on_failure']
   37:    ]
   38:    supports :report => true, :exception => true
   39:    action :nothing
   40>> end.run_action(:enable) if node['datadog']['chef_handler_enable']
   41:  
```

As a workaround, reverting to 1.1.8 resolved the issue.

**Comment by kbaltrinic** [comment]
FYI.  It looks like this may be our fault.  It appears we are using an out of date fork of the underlying datadog cookbook.  Will close this if I am able to confirm that.

**Comment by ksubrama** [comment]
The dd-handler recipe also seems to have a "require ..." lines that used to be there to work around the fact that module loading was a bit broken in the previous release of the cookbook.  You may/may not require it any more.

**Comment by mihasya** [comment]
This appears to break our (Opsmatic's) chef-handler as well. We separate the version into a separate file with the honest good intentions of one day incrementing it using CI, and then doing `require 'chef/handler/opsmatic_version'` (see [here](https://github.com/opsmatic/chef-handler-opsmatic/blob/master/lib/chef/handler/opsmatic.rb#L7) and [here](https://github.com/opsmatic/chef-handler-opsmatic/blob/master/lib/chef/handler/opsmatic_version.rb).

Is there something we need to change about the way we're doing the require in order to make this work for both pre and post 1.1.9? I tried to figure it out by just reading the patches, but got a bit lost. Thanks!

**Comment by ksubrama** [comment]
Oh drat I see what's going on.
The original intent of the module loading code in chef_handler was to completely unload the class indicated by the name of the chef_handler resource and then reload the file indicated (either by absolute path or from a gem path).  This way, if the handler got updated, during convergence, the newer version could be used.  At least, that's what I thought the intention behind all that code was.  That code is convoluted because it needs to manually unload the class name indicated and then use load instead of require (require won't reload a file it has previously loaded) to pull in the new definition.  The previous versions of this repo failed to do this and would silently fail - so consumers simply came to expect some staleness whenever handlers where being updated during a chef run.  My patch fixes this, but in the process, I seem to have broken anyone who uses a "require" in their handler class to extend their handler class.  Since "require" doesn't re-open files, you got a version of your class without that constant.

A guess a work-around for now would be to change your version file to:
```
class Chef
  class Handler
    class Opsmatic < ::Chef::Handler
      VERSION = "0.0.19" unless defined?(VERSION)
    end
  end
end
```
and changing the require into a load.

I'll try to consult with some of our head-chefs to see if there's a better way to do this in the future.

**Comment by coderanger** [comment]
All this reloading code predates forking mode in chef-client and might just not be needed anymore.

**Comment by mihasya** [comment]
Any more input from folks? I'm happy to change the Opsmatic reporter to use `load` instead of `require`, but am not sure that's the correct path long-term.

**Comment by ksubrama** [comment]
Hey!  Sorry for the delay.  I think we're leaning towards completely removing all the whacky class loading functionality seeing as we don't share processes between runs in chef-client any more.  We'll just mark the cookbook Chef 12+.  From your end, you don't need to use load instead of require - require is probably the right way to go.  I'll try to get a release out either today or early next week.
